/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Book = IDL.Record({
  'title' : IDL.Text,
  'bookType' : IDL.Text,
  'role' : IDL.Text,
  'description' : IDL.Text,
});
export const BookLink = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'storeName' : IDL.Text,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : Time,
  'published' : IDL.Bool,
  'category' : IDL.Text,
});
export const Quote = IDL.Record({
  'text' : IDL.Text,
  'isOwn' : IDL.Bool,
  'attribution' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateBook' : IDL.Func([Book], [], []),
  'createOrUpdateBookLink' : IDL.Func([BookLink], [], []),
  'createOrUpdatePost' : IDL.Func([BlogPost], [], []),
  'createOrUpdateQuote' : IDL.Func([Quote], [], []),
  'getAllBookLinks' : IDL.Func([], [IDL.Vec(BookLink)], ['query']),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
  'getBookLink' : IDL.Func([IDL.Text], [BookLink], ['query']),
  'getBooksByRole' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessage' : IDL.Func([IDL.Principal], [ContactMessage], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getOwnQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getPublishedPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getQuote' : IDL.Func([IDL.Text], [Quote], ['query']),
  'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitMessage' : IDL.Func([ContactMessage], [], []),
  'subscribe' : IDL.Func([IDL.Text], [], []),
  'unsubscribe' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Book = IDL.Record({
    'title' : IDL.Text,
    'bookType' : IDL.Text,
    'role' : IDL.Text,
    'description' : IDL.Text,
  });
  const BookLink = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'storeName' : IDL.Text,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : Time,
    'published' : IDL.Bool,
    'category' : IDL.Text,
  });
  const Quote = IDL.Record({
    'text' : IDL.Text,
    'isOwn' : IDL.Bool,
    'attribution' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateBook' : IDL.Func([Book], [], []),
    'createOrUpdateBookLink' : IDL.Func([BookLink], [], []),
    'createOrUpdatePost' : IDL.Func([BlogPost], [], []),
    'createOrUpdateQuote' : IDL.Func([Quote], [], []),
    'getAllBookLinks' : IDL.Func([], [IDL.Vec(BookLink)], ['query']),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
    'getBookLink' : IDL.Func([IDL.Text], [BookLink], ['query']),
    'getBooksByRole' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessage' : IDL.Func([IDL.Principal], [ContactMessage], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getOwnQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getPublishedPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getQuote' : IDL.Func([IDL.Text], [Quote], ['query']),
    'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitMessage' : IDL.Func([ContactMessage], [], []),
    'subscribe' : IDL.Func([IDL.Text], [], []),
    'unsubscribe' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };