/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'title' : string,
  'body' : string,
  'date' : Time,
  'published' : boolean,
  'category' : string,
}
export interface Book {
  'title' : string,
  'bookType' : string,
  'role' : string,
  'description' : string,
}
export interface BookLink {
  'url' : string,
  'title' : string,
  'description' : string,
  'storeName' : string,
}
export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Quote {
  'text' : string,
  'isOwn' : boolean,
  'attribution' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateBook' : ActorMethod<[Book], undefined>,
  'createOrUpdateBookLink' : ActorMethod<[BookLink], undefined>,
  'createOrUpdatePost' : ActorMethod<[BlogPost], undefined>,
  'createOrUpdateQuote' : ActorMethod<[Quote], undefined>,
  'getAllBookLinks' : ActorMethod<[], Array<BookLink>>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getAllQuotes' : ActorMethod<[], Array<Quote>>,
  'getBook' : ActorMethod<[string], Book>,
  'getBookLink' : ActorMethod<[string], BookLink>,
  'getBooksByRole' : ActorMethod<[string], Array<Book>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessage' : ActorMethod<[Principal], ContactMessage>,
  'getMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getOwnQuotes' : ActorMethod<[], Array<Quote>>,
  'getPost' : ActorMethod<[string], BlogPost>,
  'getPublishedPosts' : ActorMethod<[], Array<BlogPost>>,
  'getQuote' : ActorMethod<[string], Quote>,
  'getSubscriberCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitMessage' : ActorMethod<[ContactMessage], undefined>,
  'subscribe' : ActorMethod<[string], undefined>,
  'unsubscribe' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];